### ISSUE TITLE
About the old versions

### ISSUE THREAD

**Issue by kennynaoh** [recyclejs/recycle#12]
Hello @domagojk , I am the member of cdnjs project. We want to host this library. There is a question want to ask. I found that there is no `recycle.js` in `v0.2.1`~`v0.3.1` and `v0.5.0` on npm. Please help me confirm that which file I need to add in these versions. Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/10053

**Comment by domagojk** [comment]
@kennynaoh Recycle started as my personal project, and well... I'm sorry to say, I just didn't thought about cdn :/
Entry point is `index.js` but its dependencies changed over time. The main problem is that bundled minified and unminified versions (including RxJS, cycle.js or later React) were never published on npm.

What I can do now is publish `dist/recycle.js` and `dist/recycle.min.js` for next versions and send you a zip of all previous bundled versions. Would that be ok?

**Comment by kennynaoh** [comment]
@domagojk Sure, thanks for that!

**Comment by domagojk** [comment]
@kennynaoh Sorry it took me this long...
As of version 0.7.1, there is UMD build in `dist/recycle.js` and `dist/recycle.min.js` and new versions will continue to follow this practice.

Unfortunately, there is no "clean way" of providing UMD build for older versions. The problem is that usage with React and RxJS was not supported when provided as arguments, so I think that versions should not be hosted.

I hope that is not a problem?
