### ISSUE TITLE
Why you removed adapters?

### ISSUE THREAD

**Issue by goodmind** [recyclejs/recycle#14]
So, how to use this library with different streams. I come from cycle.js and this is really killer-feature for me as well as better effects handling (drivers)

**Comment by domagojk** [comment]
@goodmind 
concept with drivers from previous version was a very complex one. I was basically recreating how React works, dealing with all kinds of problems (determining which component should be updated on rerendering, keeping track of element keys for preserving component state and similar). 

Also, as I was using it, I found that "everything is a stream" mantra popularised by Cycle just made things more complicated. In the end, I used only two streams: state and actions (which is why Redux is supported). 
For side effects I would just listen on component dispatched actions and use redux-observable or similar.

However, you can still use any stream you want, but it's up to you to "wire them up". You can pass them as params in some kind of factory function or similar.

**Comment by goodmind** [comment]
But you can use `Symbol.observable` to return ES compatible observable with `subscribe`  method

**Comment by domagojk** [comment]
I thought you were referring to drivers for handling side-effects by providing streams to every component. 

But that is another issue, I now see what you mean. 

I plan to support other stream libraries by using [redux observable](https://github.com/redux-observable/redux-observable) concept, but I'm not sure yet. I will consider your proposal with `Symbol.observable` as well.

Also, if you wish, feel free to send your PR for this.

**Comment by goodmind** [comment]
Well, I tried to do something with differents stream and it looks like it even works without interop:
```
Rx.Observable.merge(xs.of(1), xs.of(2)).subscribe(console.log) 
/*
1
2
*/
```
