### ISSUE TITLE
i think u should remove the information about the `jsx` param in Hello World

### ISSUE THREAD

**Issue by faceyspacey** [recyclejs/recycle#6]
it's just unnecessary confusion at that point in time, especially if the user isn't expected to use it.

**Comment by faceyspacey** [comment]
i think in general, if you can make this all work in regular React without any of your own custom transpilation, you're on to something. 

If the custom transpilation only servers the purpose of being able to tack on reducers and actions methods to each component method, then you're better off just as a library of HOCs. I know the idea is to make this clean flat class with actions and reducers right next to the "render/view" method, but from a marketing perspective I think the *cons* of having to do custom transpilation and conversion between recycle and react components outweigh that. 

I don't see why your framework can't be rewritten as a library of higher order components. I'm sure there is a few more aspects about how you do things which depend on custom transpilation that I'm missing. But I bet we also can come up with solutions for them. 

So why not:

```
connect({
   storePath: 'todos',
   reducers() {},
   actions() {},
})(MyComponent)
```

of if u wanna look more like Redux:

```
connect( 'todos.foo',  actions,  reducers)(MyComponent)
```

In that case, you're almost identical to Redux, except that you take a key path. And of course actions and reducers mean something different.

**Comment by domagojk** [comment]
`jsx` param is obsolete now.
As for suggested API for `connect`, I understand it would be more familiar, but I'm against it. 

I want every component to have ability of passing `props` object. There are many things for which that is usefull, for example, [store plugin](https://github.com/recyclejs/recycle/blob/master/examples/TodoMVC-Store-2/containers/Todo/index.js), but also for custom made plugins (I've used it several times)

Another reason why I don't want connect-like API is because is just ugly to me :)
